### ISSUE TITLE
Bad Server Content!

### ISSUE THREAD

**Issue by iatpatelishan** [nguyenvanduocit/Lynda-Downloader#1]
![image](https://cloud.githubusercontent.com/assets/8603977/9023931/6acfedde-38cf-11e5-9312-a64d1f4d1550.png)

Also if you could add Download Whole Course, Along With Exercise file then it would be great!

**Comment by iatpatelishan** [comment]
This error is specific to this course! 
Anyways, Download whole course via IDM or Grab all mp4 urls, would be nice idea!

**Comment by nguyenvanduocit** [comment]
Thanks for report, my account at lynda was expired., I will check for thí bug soon
