### ISSUE TITLE
Not Working With Lynda New Update site

### ISSUE THREAD

**Issue by razanaiyar** [nguyenvanduocit/Lynda-Downloader#4]
please update the Lynda-Downloader because it is not working please update it as soon as possible

**Comment by nguyenvanduocit** [comment]
My account has expired, I can fix it if someone let me borrow their account for a few days

**Comment by razanaiyar** [comment]
can you contact me on facebook/raza.naiyar

**Comment by razanaiyar** [comment]
it is due to lynda update his website can you give me your facebook id

**Comment by razanaiyar** [comment]
can you give me your facebook id ?

**Comment by Karalayah** [comment]
Also following this. Lynda changed something and now the downloader doesn't work anymore. How can to share account with you? (or do you have already one?)

**Comment by iatpatelishan** [comment]
I can help you with account. Add me on fb.com/iatpatelishan

**Comment by razanaiyar** [comment]
yes contact fb/raza.naiyar

**Comment by nguyenvanduocit** [comment]
Please send you account information to my email, nguyenvanduocit@gmail.com

**Comment by Karalayah** [comment]
never mind, I'd rather not actually. Thanks

**Comment by razanaiyar** [comment]
when you will update it?

**Comment by nguyenvanduocit** [comment]
sory, nobody help me. So that, i can not fix issues.

**Comment by nguyenvanduocit** [comment]
I got an account yesterday,  I just try to download more than ten courses, and everything works very well. Can you help me to send me the link which you got error with this? Please.

**Comment by razanaiyar** [comment]
i have already send you the login details via ur email if add with me at my facebook/Raza.Naiyar so i will give you quicke response and send you the login details and help you

**Comment by razanaiyar** [comment]
![picture2](https://cloud.githubusercontent.com/assets/16797984/12546101/4cd039fe-c369-11e5-98ee-391190824bde.png)

**Comment by iatpatelishan** [comment]
This new layout is not seen in my computer! o.O
So new theme is issue

**Comment by razanaiyar** [comment]
yup and you get the benefits right

**Comment by Karalayah** [comment]
so the question is, can the tool be adjusted to the new lay out, or can we change the lay out to get back the old one?

**Comment by nguyenvanduocit** [comment]
@razanaiyar sorry, I don't accept friend request if i don't know about you. by the way, @iatpatelishan gave me his account.
And new layout is not seen in my computer too, This extension work fine with me. If this layout only shown for you account, please send me your account information to my email address.

**Comment by Karalayah** [comment]
When I'm signed out and go to a certain course, I see it in the old lay out, and with your tool I can download course. Of course, since I'm not signed in, I can only download the public courses and the other ones show as 'fetching'. Though when I sign in, the lay out changes, and your tool is nowhere in sight...

**Comment by nguyenvanduocit** [comment]
I guest new layout only apply for some account.

**Comment by Karalayah** [comment]
In Internet Explorer it shows the old lay out, but your tool is only for Chrome, right? :-)

**Comment by nguyenvanduocit** [comment]
This is an extension for chrome. so, it don't work on IE, firefox

**Comment by razanaiyar** [comment]
its okay no problem but i will introduce my self there..

**Comment by nguyenvanduocit** [comment]
When i login with iatpatelishan's account. I don't se the new layout, it's old layout. So that, I can not fix issue happens on new layout.

**Comment by razanaiyar** [comment]
i am using the trial version so can also make a free trial and will see the new look like above i share

**Comment by nguyenvanduocit** [comment]
iatpatelishan's account is trial too.

**Comment by razanaiyar** [comment]
so then its not look like same is this due country change ?

**Comment by nguyenvanduocit** [comment]
What is you country name ?

**Comment by razanaiyar** [comment]
Pakistan and he is in india my neibour

**Comment by nguyenvanduocit** [comment]
Lol, Lynda.com error. I can not change contry. https://www.evernote.com/l/AsWjhOZau2lJ7Lr1Glp5t4d2Oz6OdAwDcPsB/image.png

**Comment by razanaiyar** [comment]
what is your country ? wait i change my country to uk or usa then i try what they show me

**Comment by razanaiyar** [comment]
nothing change all are same like my country when i change my ip to usa or uk

**Comment by nguyenvanduocit** [comment]
vietnam

**Comment by Ashish-dawani** [comment]
Please Update your downloader! it is not working with new layout!

**Comment by razanaiyar** [comment]
another complaint bro nguyenvanducit

**Comment by Ashish-dawani** [comment]
hope you fix it soon brother!

**Comment by vuxuanphat0203** [comment]
em cũng bị tình trạng tương tự, trước khi đang nhap thì giao diện cũ, khi đang nhap no chuyen thanh giao dien mới

**Comment by nguyenvanduocit** [comment]
ok guys, Lynda update new layout for me now. I will fix this bug soon. I have to keep the extension work with two layout

**Comment by vuxuanphat0203** [comment]
cam on anh rat nhieu

**Comment by Karalayah** [comment]
Great nguyenvanduocit. Good luck with it and thanks!

**Comment by razanaiyar** [comment]
wow that too much great bro we will wait please quickly do it as soon as possible God Bless You Bro thanksssssss a lot

**Comment by Karalayah** [comment]
Looking forward! Thanks a lot :-)

**Comment by razanaiyar** [comment]
@nguyenvanduocit do you have the lynda account login detail??? if no contact me on facebook or here... my FB id is mention above check it there thanks and please work on it quickly

**Comment by nguyenvanduocit** [comment]
I have lynda account now. I am fixing

**Comment by vuxuanphat0203** [comment]
anh co email ko ạ, em co the gui cho a qua đó

**Comment by razanaiyar** [comment]
okay thanks a lot dear bro @nguyenvanduocit

**Comment by Ashish-dawani** [comment]
Great Brother! Thanks!

**Comment by razanaiyar** [comment]
plz quickly

**Comment by Ashish-dawani** [comment]
Any Progress???

**Comment by razanaiyar** [comment]
where is the owner why not response what happened

**Comment by razanaiyar** [comment]
we need to close this issue bcz no response from the owner @nguyenvanduocit

**Comment by samfar22** [comment]
Although this Chrome extension was fine once it was working, but a much better and more flexible tool to download from many websites including Linda is youtube-dl (https://rg3.github.io/youtube-dl/). I has many fantastic features (including full downloading of multiple courses with a single command) and often gets updated daily. You first need to read the documentation to realize how to leverage its features.

**Comment by razanaiyar** [comment]
what the hell is there

**Comment by Deadlyhacker** [comment]
Owner of the project died with his project guys so :-1:

**Comment by razanaiyar** [comment]
yah may be he is died and no response

**Comment by nguyenvanduocit** [comment]
Sorry guys. I am port it in to golang. give me a time. I will deploy it in to cloud, then you can download video without account.

**Comment by vuxuanphat0203** [comment]
van ho tro transcript phai ko anh

**Comment by razanaiyar** [comment]
When ???? after expiration of our accounts ????? Come do it fast yarrrrrrr

**Comment by razanaiyar** [comment]
when to complete bro?????

**Comment by razanaiyar** [comment]
When ???? after expiration of our accounts ????? Come do it fast yarrrrrrr

**Comment by razanaiyar** [comment]
When ???? after expiration of our accounts ????? Come do it fast yarrrrrrr

**Comment by white-zero** [comment]
@razanaiyar have you paid him? he did this work for us in his free time and he is not charing a single cent from us. Why you are making such noise?

**Comment by iatpatelishan** [comment]
exactly white-zero -_- bored of this guy. if you are too eager @razanaiyar
then hire some developer and make extension for yourself.

**Comment by nguyenvanduocit** [comment]
WTF. The video intro of this extension had been reported, My channel is restricted.
I don't have time to fix this extension, then you report my youtube channel.
I spend my time to create this extension. When I have no time to maintain it. You report my Channel? WTF.
You can see, My video have no ads now. yeah, you success.

**Comment by nguyenvanduocit** [comment]
I decided to delete this repo.
