### ISSUE TITLE
Not working after Lynda's recent update to their website layout

### ISSUE THREAD

**Issue by samfar22** [nguyenvanduocit/Lynda-Downloader#5]
This was working fine until 2 days ago, but stopped working after Lynda updated website's layout. Please fix it. Thank you in advance. Please let me know if you need an active account.

**Comment by razanaiyar** [comment]
we already work on it and already report to the owner bro... in the 3rd Notworking name u can see all the conversation there thanks soon it will be updated two new layout and old also..... bro @samfar22 connect with me at facebook.com/Raza.Naiyar

**Comment by samfar22** [comment]
Thanks for your comment. I do not have any FB account.
